# Generated by Django 5.0.13 on 2026-02-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_index', models.IntegerField(verbose_name='조건식인덱스')),
                ('condition_name', models.CharField(max_length=200, verbose_name='조건식명')),
                ('is_realtime', models.BooleanField(default=True, verbose_name='실시간조건검색')),
                ('auto_trade', models.BooleanField(default=False, verbose_name='자동매매여부')),
                ('status', models.CharField(choices=[('active', '실행중'), ('stopped', '중지'), ('error', '오류')], default='stopped', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '조건검색식',
                'verbose_name_plural': '조건검색식 목록',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('market', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장구분')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '종목',
                'verbose_name_plural': '종목 목록',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='기본설정', max_length=100, verbose_name='설정명')),
                ('trade_mode', models.CharField(choices=[('mock', '모의투자'), ('real', '실투자')], default='mock', max_length=10, verbose_name='투자모드')),
                ('app_key', models.CharField(blank=True, max_length=200, verbose_name='APP KEY')),
                ('app_secret', models.CharField(blank=True, max_length=200, verbose_name='APP SECRET')),
                ('account_no', models.CharField(blank=True, max_length=20, verbose_name='계좌번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('max_buy_amount', models.IntegerField(default=1000000, verbose_name='최대매수금액')),
                ('max_buy_per_stock', models.IntegerField(default=500000, verbose_name='종목당최대매수금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '매매설정',
                'verbose_name_plural': '매매설정 목록',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', '매수'), ('sell', '매도')], max_length=4, verbose_name='주문유형')),
                ('price_type', models.CharField(choices=[('limit', '지정가'), ('market', '시장가')], default='market', max_length=10, verbose_name='가격유형')),
                ('quantity', models.IntegerField(verbose_name='주문수량')),
                ('price', models.IntegerField(default=0, verbose_name='주문가격')),
                ('filled_quantity', models.IntegerField(default=0, verbose_name='체결수량')),
                ('filled_price', models.IntegerField(default=0, verbose_name='체결가격')),
                ('status', models.CharField(choices=[('pending', '대기'), ('submitted', '접수'), ('filled', '체결'), ('partial', '부분체결'), ('cancelled', '취소'), ('rejected', '거부')], default='pending', max_length=10, verbose_name='상태')),
                ('order_no', models.CharField(blank=True, max_length=20, verbose_name='주문번호')),
                ('trade_mode', models.CharField(default='mock', max_length=10, verbose_name='투자모드')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='주문사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stock.conditionsearch', verbose_name='조건검색식')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock.stock', verbose_name='종목')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConditionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('I', '편입'), ('D', '이탈')], max_length=1, verbose_name='편입/이탈')),
                ('matched_at', models.DateTimeField(auto_now_add=True, verbose_name='검출시각')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stock.conditionsearch', verbose_name='조건검색식')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_matches', to='stock.stock', verbose_name='종목')),
            ],
            options={
                'verbose_name': '조건검색 결과',
                'verbose_name_plural': '조건검색 결과 목록',
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(default=0, verbose_name='현재가')),
                ('open_price', models.IntegerField(default=0, verbose_name='시가')),
                ('high_price', models.IntegerField(default=0, verbose_name='고가')),
                ('low_price', models.IntegerField(default=0, verbose_name='저가')),
                ('prev_close', models.IntegerField(default=0, verbose_name='전일종가')),
                ('volume', models.BigIntegerField(default=0, verbose_name='거래량')),
                ('change_rate', models.FloatField(default=0.0, verbose_name='등락률')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='시세시각')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock.stock')),
            ],
            options={
                'verbose_name': '시세',
                'verbose_name_plural': '시세 목록',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=4, verbose_name='매매유형')),
                ('quantity', models.IntegerField(verbose_name='체결수량')),
                ('price', models.IntegerField(verbose_name='체결가격')),
                ('total_amount', models.IntegerField(default=0, verbose_name='체결금액')),
                ('trade_mode', models.CharField(default='mock', max_length=10, verbose_name='투자모드')),
                ('traded_at', models.DateTimeField(auto_now_add=True, verbose_name='체결시각')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='stock.order', verbose_name='주문')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stock.stock', verbose_name='종목')),
            ],
            options={
                'verbose_name': '체결내역',
                'verbose_name_plural': '체결내역 목록',
                'ordering': ['-traded_at'],
            },
        ),
        migrations.AddField(
            model_name='conditionsearch',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='stock.tradingconfig', verbose_name='매매설정'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='보유수량')),
                ('avg_price', models.IntegerField(default=0, verbose_name='평균매입가')),
                ('current_price', models.IntegerField(default=0, verbose_name='현재가')),
                ('profit_rate', models.FloatField(default=0.0, verbose_name='수익률')),
                ('profit_amount', models.IntegerField(default=0, verbose_name='평가손익')),
                ('trade_mode', models.CharField(default='mock', max_length=10, verbose_name='투자모드')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='stock.stock', verbose_name='종목')),
            ],
            options={
                'verbose_name': '잔고',
                'verbose_name_plural': '잔고 목록',
                'unique_together': {('stock', 'trade_mode')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='conditionsearch',
            unique_together={('condition_index', 'condition_name')},
        ),
    ]
